config/routes.rb
Gestor::Application.routes.draw do
  
  get "estado_recrut/new"

  get "estado_recrut/create"

  get "estado_recrut/destroy"

  get "estado_recrut/edit"

  resources :estados

  resources :candidatos do
    member do
      post :guardar_survey
      post :guardar_cand_fora_epoca
    end
  end

  get "recrutamento/create"

  get "recrutamento/new"

  resources :pergunta_forms do
    member do
      post :edit_pergunta_form
    end
  end

  get "password_resets/new"

  resources :pergunta do
    member do
      post :importar_pergunta_form
    end
  end

  get "sessions/new"

  resources :comites do
    member do
      post :guardar
      post :reorder
      post :reorderEstados
      get :abrir_recrutamento
      post :add_estado
    end
  end

  resources :recrutamento
  
  resources :estado_recrut do
    member do
      post :create_estado
      put :update_estado
    end
  end

  get "abrir_recrutamento" => "recrutamento#abrir_recrutamento_m"
  get "abrir_inscricoes" => "recrutamento#abrir_inscricoes"
  get "fechar_inscricoes" => "recrutamento#fechar_inscricoes"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "comites#new", :as => "sign_up"

  get "inscricoes" => "comites#inscricoes", :as => "inscricoes"
  get "profile" => "comites#show", :as => "profile"

  post "pre_vis_survey" =>"comites#pre_vis_survey", :as => "pre_vis_survey"
  

  get "perguntas_comite/:id" => "pergunta#perguntas_comite",:as =>"perguntas_comite"

  
  get "formulario_membros/:id" => "comites#formulario_membros",:as =>"formulario_membros"
  get "formulario_estagios/:id" => "comites#formulario_estagios",:as =>"formulario_estagios"
  
  get "comites/:id/survey" => "comites#survey",:as =>"survey"

  get "candidatos_membros" => "candidatos#candidatos_membros" , as: "candidatos_membros"
  get "candidatos_estagios" => "candidatos#candidatos_estagios" , as: "candidatos_estagios"
  get "candidatos_fora_epoca" => "candidatos#candidatos_fora_epoca" , as: "candidatos_fora_epoca"

  get "recrutamento_membros" => "recrutamento#recrutamento_membros" , as: "recrutamento_membros"
  get "recrutamento_estagios" => "recrutamento#recrutamento_estagios" , as: "recrutamento_estagios"

  post "survey" => "candidatos#survey",:as =>"survey"
  get "inscricao" => "candidatos#inscricao",:as =>"inscricao"
  get "survey_final" => "candidatos#survey_final",:as =>"survey_final"
  get "help" => "comites#help",:as =>"help"
  get "dashboard" => "comites#dashboard",:as =>"dashboard"

  post "edit_candidatos" =>"candidatos#edit_candidatos"

  resources :sessions

   root :to => 'comites#dashboard'

end

app/models/comite.rb
# -*- encoding : utf-8 -*-
class Comite < ActiveRecord::Base
  attr_accessible :descricao, :email, :email_ocp, :morada, :nome, :telefone,:password, :password_confirmation

  
  attr_accessor :password
  
  
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  validates_format_of :email_ocp, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :nome
  validates_uniqueness_of :nome

  before_save :encrypt_password

  has_many :formularios
  has_many :recrutamento
  has_many :estado_recrut


  def self.authenticate(nome, password)
    comite = find_by_nome(nome)
    if comite && comite.password_hash == BCrypt::Engine.hash_secret(password, comite.password_salt)
      comite
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  #funcao que verifica se tem inscriçoes activas
  def inscricao_activa?(tipo)
    r = self.recrutamento.recrutamento_activo(tipo)

    if !r.nil?
      return r.inscricao_activa_recrut?
    else
      return false
    end
  end

  #cria um novo formulario
  def cria_formulario(tipo,comite_id,recrutamento_id)
    if tipo == 1
          nome = "Formulario Membros"
    else
          nome = "Formulario Estagios"
    end
    
    self.formularios.build(:nome=>nome,:comite_id=> comite_id,:tipo=>tipo,:recrutamento_id=>recrutamento_id)
  end 


  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Comite.exists?(column => self[column])
  end

  def cenas
        obj1 = Array.new
        num_anuncios = Comite.all.count
        Comite.all.each do |c|
          val = (100 / 40) * 100

          obj1.push([ c.nome, val ])
        end

        return obj1
  end


  def candidatos_por_recrutamento(idC,tipo)
    obj = Array.new

    Recrutamento.where(:comite_id => idC,:tipo =>tipo).each do |r|
      num_cand = r.candidatos.count
      obj.push([ r.created_at.strftime('%d/%m/%Y'), num_cand ])
    end

    return obj
  end


end

app/controllers/comites_controller.rb
# -*- encoding : utf-8 -*-
class ComitesController < ApplicationController
  # GET /comites
  # GET /comites.json
  before_filter :correct_comite, :only => [ :edit, :destroy,:abrir_recrutamento]
  
  skip_before_filter :authorize, :only => [:new,:create]


  def index
    @comites = Comite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comites }
    end
  end

  # GET /comites/1
  # GET /comites/1.json
  def show
    @comite = !params[:id].nil? ? Comite.find(params[:id]) : current_comite

    @stats = @comite.candidatos_por_recrutamento(current_comite.id,1)

    @estado_recrut = EstadoRecrut.new
    @estados_membros = EstadoRecrut.find(:all,:conditions =>["comite_id = ? and tipo = 1 and activo = 1",@comite.id])
    @estados_estagios = EstadoRecrut.find(:all,:conditions =>["comite_id = ? and tipo = 2 and activo = 1",@comite.id])

    
    @h = pie_plot(@stats,"cenas")
    @h1 = column_plot1(@stats,"")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comite }
    end
  end

  

  #metodo que guarda a ordem das perguntas 
  #com o drag&drop podemos alterar a sua ordem
  #no javascript é lancado um pedido para para executar este metodo
  #o js manda um array com os valores dos id' s das perguntas
  #ex params[:respostas]=[2,4,5]
  #ele vai a cada uma das perguntas e altera a sua ordem
  def reorder
    perguntas_ids = params[:perguntas]
    n = 1
    ActiveRecord::Base.transaction do
      perguntas_ids.each do |id|
        if !id.blank?
          pergunta = PerguntaForm.find(id)
          pergunta.ordem = n
          pergunta.save
          n += 1
        end
      end
    end
    render :json => {}
  end

  def reorderEstados
    estados_ids = params[:estados]
    n = 1
    ActiveRecord::Base.transaction do
      estados_ids.each do |id|
        if !id.blank?
          estado_recrut = EstadoRecrut.find(id)
          estado_recrut.ordem = n
          estado_recrut.save
          n += 1
        end
      end
    end
    render :json => {}
  end

  #formularios membros tipo = 1
  #/formulario_membros/:id para ver o formulario de um comite
  def formulario_membros
    
    @comites = Comite.find(:all,:select=>"id,nome")                #select id,nome from ...
    @comite = Comite.find_by_id(params[:id])                       #seleciona o comite pelo o id que esta no request
    
    @formulario = @comite.formularios.formulario_activo(1)         #vai buscar o formulario que esta activo

    @recrutamento = @formulario.recrutamento  unless  @formulario.nil?
    
    @perguntum = Perguntum.new
    @pergunta_form = PerguntaForm.new

  end

  #formularios estagios tipo = 2
  #/formulario_estagio/:id para ver o formulario de um comite
  def formulario_estagios
    @comites = Comite.find(:all,:select=>"id,nome")                #select id,nome from ...
    @comite = Comite.find_by_id(params[:id])                       #seleciona o comite pelo o id que esta no request
    
    @formulario = @comite.formularios.formulario_activo(2)         #vai buscar o formulario que esta activo de estagio que é o 2
    @recrutamento = @formulario.recrutamento  unless  @formulario.nil?
 
    @perguntum = Perguntum.new
    @pergunta_form = PerguntaForm.new
    
  end

  #serve para abrir um recrutamento e criar novos formularios
  def abrir_recrutamento

    tipo = params[:tipo].to_i                                         #tipo=1 é pra membros e tipo=2 é pra estagios
    @comite = Comite.find_by_id(params[:id])                          #seleciona o comite pelo o id que esta no request
    @formulario = @comite.formularios.formulario_activo(tipo)         #vai buscar o formulario que esta activo de membros
    
    if tipo == 1
      @formulario_membro_novo  = @comite.formularios.build(:nome=>"Formulario Membros",:comite_id=> @comite.id,:tipo=>1)
    else
      @formulario_membro_novo  = @comite.formularios.build(:nome=>"Formulario Estagios",:comite_id=> @comite.id,:tipo=>2)
    end

    if !@formulario.nil?
      @formulario.estado = 0                                       #altera o estado do formulario antigo outro para 0
      @formulario.save  
    end                                                            #salva o formulario antigo
    
    @formulario_membro_novo.save                                   #guarda o formulario novo


    @formulario.pergunta_forms.each do |p|                         # copia todas as perguntas do formulario antigo para o novo
      p = @formulario_membro_novo.pergunta_forms.build(pergunta_id:p.pergunta_id,ordem:p.ordem,obrigatoria:p.obrigatoria)
      p.save
    end
    
    @formulario_membro_novo.save                                    #guarda o formulario novo

 

    respond_to do |format|
      format.html { redirect_to path }
      format.json { head :no_content }
    end

  end


 
  def guardar
      val = params[:respostas]
      @comite = Comite.find(params[:id])
      @formulario = @comite.formularios[0]
      @perguntas = @formulario.perguntum

      n = 0
      @perguntas.each do |p|
        Respostum.new(pergunta_id:params[:respostas][:id][n],resposta:params[:respostas][:resposta][n]).save
        n = n + 1
      end

      respond_to do |format|
      format.html { redirect_to resposta_path }
      format.json { head :no_content }
    end
  end


  def inscricoes
    @comite = Comite.find(current_comite)

    @recrutamento = @comite.recrutamento
  end

  
  def help
  end

  def dashboard

    # Recrutamento.all.each do |r|
    #    counter = Counter.new(:visitas => 0, :recrutamento_id => r.id )
    #    counter.save
    # end

    @counter_membr = Counter.my_find(2)
    @counter_estag = Counter.my_find(2)

    #ultimos candidatos inscritos
    @last_cand = Candidato.last_month(current_comite.id)
    
    @recrutamento_m = current_comite.recrutamento.activo_and_aberto(1)
    @recrutamento_e = current_comite.recrutamento.activo_and_aberto(2)

    


  end

  def pre_vis_survey
    @comite = Comite.find(current_comite.id)
    formulario_id = params[:formulario] 
    @formulario = Formulario.find(formulario_id)         #vai buscar o formulario que esta activo de estagio que é o 2
    
    @recrutamento = @formulario.recrutamento  unless  @formulario.nil?

    if !@formulario.nil?
        @perguntas_form = @formulario.pergunta_forms
    end

    render :layout =>"survey"
  end
  

  # GET /comites/new
  # GET /comites/new.json
  def new
    @comite = Comite.new
    render :layout =>"sign_up"
    
  end

  # GET /comites/1/edit
  def edit
    @comite = Comite.find(params[:id])
  end

  # POST /comites
  # POST /comites.json
  def create
    @comite = Comite.new(params[:comite])

    respond_to do |format|
      if @comite.save
         format.html { redirect_to log_in_path, notice: 'Comite was successfully created.' }
            format.json { render json: @comite, status: :created, location: log_in_path }
      else
        format.html { render action: "new" }
        format.json { render json: @comite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comites/1
  # PUT /comites/1.json
  def update
    @comite = Comite.find(params[:id])

    respond_to do |format|
      if @comite.update_attributes(params[:comite])
        format.html { redirect_to @comite, notice: 'Comite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comites/1
  # DELETE /comites/1.json
  def destroy
    @comite = Comite.find(params[:id])
    @comite.destroy

    respond_to do |format|
      format.html { redirect_to comites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comites_helper.rb
# -*- encoding : utf-8 -*-
module ComitesHelper


	def current_form?(id,id_com)
		if id == id_com
			return true
		else
			return false
		end
	end

	#verifica se id é igual ao comite logado
	def current_comite?(id_com)
		if id_com == current_comite.id
			return true
		else
			return false
		end
	end

	def getPathFormulario(tipo)
		if tipo == 1
			path = "formulario_membros"
		else
			path = "formulario_estagios"
		end

		return path
	end


	def tipoPerguntaToString(tipo)
		case tipo
			when 1
				"Respota Aberta"
			when 2
				"Escolha Multipla"
			when 3
				"ComboBox"
			when 4
				"Radio Box"
			when 5
				"Area de Texto"
		end
	end

	def arrayToString(opcoes)
		html = "".html_safe
		opcoes.each do |op|
			html << op.html_safe
			html << "<br>".html_safe
		end
		return html
	end

end

app/views/comites/_form.html.erb
<%= form_for(@comite) do |f| %>
  <% if @comite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comite.errors.count, "error") %> prohibited this comite from being saved:</h2>

      <ul>
      <% @comite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
 <div class="field">
   <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
   </p>
  </div>
  <div class="field">
   <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    </p>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :morada %><br />
    <%= f.text_field :morada %>
  </div>
  <div class="field">
    <%= f.label :email_ocp %><br />
    <%= f.text_field :email_ocp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comites/_show.html.erb
        <div class="header">
            <div class="stats">
                <p class="stat">Perguntas <span class="number"><%= @formulario.pergunta_forms.count %></span></p>
            </div>
          <h1 class="page-title"><%= @formulario.nome %></h1>

          
        </div>
        
        <ul class="breadcrumb">
            <li><a href="index.html">Home</a> <span class="divider">/</span></li>
            <li>Recrutamento <%= l @recrutamento.created_at , :format => :long %><span class="divider">/</span></li>
            <li class="active"><%= @formulario.nome %> <%= @formulario.id %> <%= @formulario.comite_id %></li>
        </ul>

        <div class="container-fluid">
            <div class="row-fluid">


          <div class="btn-toolbar">
            
             <form id="tab" class="inline">
                  <label>Comité</label>
                  <!-- verifica qual o tipo do formulario -->
                    <% if @formulario.tipo == 1 %>
                       <select name="DropDownComiteMembros" id="DropDownComiteMembros" class="input">
                    <% else %>
                      <select name="DropDownComiteEstagios" id="DropDownComiteEstagios" class="input">
                    <% end %>

                    <% @comites.each do |c| %> 
                      <% z = params[:id] %>
                      <% if c.nome != "Aiesec Admin" %>
                        <option value="<%= c.id %>" <%= 'selected' if current_form?(params[:id].to_i,c.id) %> ><%= c.nome %></option>
                      <% end %>
                   <% end %>
                  </select>

              </form>


              <%= form_for(:perguntas, :url => {:action => 'edit_pergunta_form',:controller => 'pergunta_forms',:id=>@formulario.id}) do |f| %>
              
            <% action = tipo_formulario?(@formulario.tipo) %>

            <div class="btn-toolbar">
              <% if current_comite?(params[:id].to_i) %>

                      <!--verifica se inscriçoes estao abertas -->
                    <div id="inscricoes_form">
                      <b>Inscrições <%= inscricoes(@recrutamento.inscricao_activa) %></b>
                      <br> <br>
                         <div >
                       
                        <b>Formulário</b>  <span class="label label-success" id="estado1">Guardado</span>
                        
                         </div>
                    </div>

                    <%# link_to '<i class="icon-plus"></i> Nova Pergunta'.html_safe, new_perguntum_path(:name=>action) ,:class=>"btn" %>

                     <a href="#myModalPergunta" data-toggle="modal" class="btn"><i class="icon-plus"></i>Nova Pergunta</a>
                    
              <% else %>
                      <%= f.submit "Exportar para meu formulário",:class=>"btn" %>

                 <% end %>
           </div>

            <p id="notice"><%= notice %></p>



          </div>
          <div class="well">
              <table id="<%= 'sortable' if current_comite?(params[:id].to_i) %>" class="table table-hover" >
                <thead>
                  <tr>
                    <th><input type="checkbox" name="select-all" id="select-all"></th>
                    <th >Título</th>
                    <th>Descriçao</th>
                    <th>Tipo</th>
                    <th>Opções</th>
                    <th>Obrigatória</th>
                    <th style="width: 26px;"></th>
                  </tr>
                </thead>
                <tbody>
                  
                     <% @formulario.pergunta_forms.each do |p| %>
                     <tr id="<%= p.id %>" class="handle">
                        <% pergunta = p.perguntum %>
                        <td><%= check_box_tag 'perguntas[]', p.id, false,:class=>"select-all" %></td>
                        <td><%= pergunta.titulo %></td>
                        <td> <%= pergunta.descricao %></td>
                        <td><%= tipoPerguntaToString( pergunta.tipo ) %></td>
                        <td>
                          <% opcoes = pergunta.opcoes.split('|') %>
                          <%= arrayToString(opcoes) %>
                        </td>
                        
                          <%= obrigatoria?(p.obrigatoria) %>
                        
                        <!--<td><%= p.ordem %></td>-->
                        <% if current_comite?(params[:id].to_i) %> 
                          <td>
                              <%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_perguntum_path(pergunta)%>
                              <%= link_to '<i class="icon-remove"></i>'.html_safe, p, method: :delete, data: { confirm: 'Are you sure?' } %>
                          </td>
                        <% end %>
                    </tr>
                     <% end %>

                    
                </tbody>
              </table>
          </div>

            <div class="btn-toolbar">
              <!-- se nao for do comite que tem login feito nao pode alterar o formulario -->
              <% if current_comite?(params[:id].to_i) %>

                <span class="label label-success" id="estado">Guardado</span>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-primary" id="guardar" href="#" title="ctrl + s para guardar"><i class="icon-save"></i> Guardar</button>



                <div class="btn-toolbar">
                    <a href="#askDialogDel" data-toggle="modal" class="btn">Remover</a>
                    <%= f.submit "Obrigatoria",:class=>"btn " %>
                    <%= f.submit "Opcional",:class=>"btn btn-primary" %>


                    <%= link_to '<i class="icon-drink"></i>Pré-visualizar Formulário'.html_safe,pre_vis_survey_path(:formulario => @formulario.id) ,:method => :post , :class=>"btn" %>
              <% end %><!--fim da condicao-->

            </div>
          </div>

               <!-- Modal NOVA PERGUNTA-->
              <div id="askDialogDel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="windowTitleLabel" aria-hidden="true">
                  <div class="modal-header">
                  <a href="#" class="close" data-dismiss="modal">&times;</a>
                  <h3 id="askDialogPrompt"> </h3>
                  </div>
                  <div class="modal-body" id="askDialogDel">
                    Tem a certeza que pretende remover as perguntas?
                  </div>


                  <div class="modal-footer">
                  <%= f.submit "Remover",:class=>"btn btn-danger",data: { confirm: 'Are you sure?' } %>
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                  </div>
            </div>
             


            <% end %> <!-- fim do fromulario -->


            

        
        <div id="myModalPergunta" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel">Nova Pergunta</h3>
            </div>
            <div class="modal-body">
               <%= render :partial=>'pergunta/form'  %>
            </div>
          </div>

app/views/comites/formulario_estagios.html.erb
<% if @formulario.nil? %>
	<div id="perguntas">

        
         <h1 class="page-title">Formulário</h1>
        <ul class="breadcrumb">
            <li><a href="index.html">Home</a> <span class="divider">/</span></li>
        </ul>
         <div class="container-fluid">
            <div class="row-fluid">
                <div class="btn-toolbar">
                    
                     <form id="tab" class="inline">
                          <label>Comité</label>
                          <!-- verifica qual o tipo do formulario -->
                            <% if current_page?(candidatos_membros_path) %>
                               <select name="DropDownComiteMembros" id="DropDownComiteMembros" class="input">
                            <% else %>
                              <select name="DropDownComiteEstagios" id="DropDownComiteEstagios" class="input">
                            <% end %>

                            <% @comites.each do |c| %> 
                              <% z = params[:id] %>
                              <% if c.nome != "Aiesec Admin" %>
                                <option value="<%= c.id %>" <%= 'selected' if current_form?(params[:id].to_i,c.id) %> ><%= c.nome %></option>
                              <% end %>
                           <% end %>
                          </select>
                      </form>

		<h1>Nao existem formularios</h1>
	</div>
<% else %>
	<div id="perguntas">
		<%= render 'show' %>
	</div>
<% end %>

app/views/comites/formulario_membros.html.erb
<% if @formulario.nil? %>
	<div id="perguntas">
		<div class="header">
            <div class="stats">
                <p class="stat"><span class="number"><%= @formulario.pergunta_forms.count %></span> Perguntas</p>
         </div>
          <h1 class="page-title"><%= @formulario.nome %></h1>

          
        </div>
        
	        <ul class="breadcrumb">
	            <li><a href="index.html">Home</a> <span class="divider">/</span></li>
	            <li>Recrutamento <%= l @recrutamento.created_at , :format => :long %><span class="divider">/</span></li>
	            <li class="active"><%= @formulario.nome %> <%= @formulario.id %> <%= @formulario.comite_id %></li>
	        </ul>
		<h1>Nao existem formularios</h1>
	</div>
<% else %>
	<div id="perguntas">
		<%= render 'show' %>
	</div>
<% end %>

app/views/comites/formulario_membros.js.erb
$("#perguntas").html("<%= escape_javascript(render 'show') %>");

app/views/comites/formulario_outros.html.erb
<div id="perguntas">
	<%= render 'show' %>
</div>

<%= link_to 'Back', comites_path %>

app/views/comites/index.html.erb
        <div class="header">
            
            
        <h1 class="page-title">Comites</h1>
        </div>
        
                <ul class="breadcrumb">
            <li><a href="index.html">Home</a> <span class="divider">/</span></li>
            <li class="active">Comites</li>
        </ul>



<div class="container-fluid">     
   <form id="tab">
      <div class="well">        
            <table class="table">
              <tr>
                <th>Nome</th>
                <th>Descricao</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Morada</th>
                <th>Email ocp</th>
                <th></th>
                <th></th>
              </tr>

            <% @comites.each do |comite| %>
              <tr>
                <td><%= comite.nome %></td>
                <td><%= comite.descricao %></td>
                <td><%= comite.email %></td>
                <td><%= comite.telefone %></td>
                <td><%= comite.morada %></td>
                <td><%= comite.email_ocp %></td>

                <td><%= link_to 'Ver', comite %></td>
                 <% if isAdmin? %> 
                    <td><%= link_to 'Edit', edit_comite_path(comite) %></td>
                 <% end %> 
              </tr>
            <% end %>
            </table>

            <br />
            <% if isAdmin? %>
             <%= link_to 'New Comite', new_comite_path %>
            <% end %>

app/views/comites/new.html.erb
<h1>New comite</h1>

 <div class="row-fluid">
    <div class="dialog">
        <div class="block">
            <p class="block-heading">Sign Up</p>
            <div class="block-body">
				<%= form_for(@comite) do |f| %>
				  <% if @comite.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@comite.errors.count, "error") %> prohibited this comite from being saved:</h2>

				      <ul>
				      <% @comite.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>

				  <div class="field">
				    <%= f.label :nome %><br />
				    <%= f.text_field :nome %>
				  </div>
				 <div class="field">
				   <p>
				    <%= f.label :password %><br />
				    <%= f.password_field :password %>
				   </p>
				  </div>
				  <div class="field">
				   <p>
				    <%= f.label :password_confirmation %><br />
				    <%= f.password_field :password_confirmation %>
				    </p>
				  </div>
				   
				  <div class="field">
				    <%= f.label :descricao %><br />
				    <%= f.text_field :descricao %>
				  </div>
				  <div class="field">
				    <%= f.label :email %><br />
				    <%= f.text_field :email %>
				  </div>
				  <div class="field">
				    <%= f.label :telefone %><br />
				    <%= f.text_field :telefone %>
				  </div>
				  <div class="field">
				    <%= f.label :morada %><br />
				    <%= f.text_field :morada %>
				  </div>
				  <div class="field">
				    <%= f.label :email_ocp %><br />
				    <%= f.text_field :email_ocp %>
				  </div>
				  <div class="actions">
				    <%= f.submit %>
				  </div>
				<% end %>
  			</div>
        </div>
        <p><a href="privacy-policy.html">Privacy Policy</a></p>
    </div>
</div>

  
             

<%= link_to 'Back', comites_path %>