config/routes.rb
Gestor::Application.routes.draw do
  
  get "estado_recrut/new"

  get "estado_recrut/create"

  get "estado_recrut/destroy"

  get "estado_recrut/edit"

  resources :estados

  resources :candidatos do
    member do
      post :guardar_survey
      post :guardar_cand_fora_epoca
    end
  end

  get "recrutamento/create"

  get "recrutamento/new"

  resources :pergunta_forms do
    member do
      post :edit_pergunta_form
    end
  end

  get "password_resets/new"

  resources :pergunta do
    member do
      post :importar_pergunta_form
    end
  end

  get "sessions/new"

  resources :comites do
    member do
      post :guardar
      post :reorder
      post :reorderEstados
      get :abrir_recrutamento
      post :add_estado
    end
  end

  resources :recrutamento
  
  resources :estado_recrut do
    member do
      post :create_estado
      put :update_estado
    end
  end

  get "abrir_recrutamento" => "recrutamento#abrir_recrutamento_m"
  get "abrir_inscricoes" => "recrutamento#abrir_inscricoes"
  get "fechar_inscricoes" => "recrutamento#fechar_inscricoes"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "comites#new", :as => "sign_up"

  get "inscricoes" => "comites#inscricoes", :as => "inscricoes"
  get "profile" => "comites#show", :as => "profile"

  post "pre_vis_survey" =>"comites#pre_vis_survey", :as => "pre_vis_survey"
  

  get "perguntas_comite/:id" => "pergunta#perguntas_comite",:as =>"perguntas_comite"

  
  get "formulario_membros/:id" => "comites#formulario_membros",:as =>"formulario_membros"
  get "formulario_estagios/:id" => "comites#formulario_estagios",:as =>"formulario_estagios"
  
  get "comites/:id/survey" => "comites#survey",:as =>"survey"

  get "candidatos_membros" => "candidatos#candidatos_membros" , as: "candidatos_membros"
  get "candidatos_estagios" => "candidatos#candidatos_estagios" , as: "candidatos_estagios"
  get "candidatos_fora_epoca" => "candidatos#candidatos_fora_epoca" , as: "candidatos_fora_epoca"

  get "recrutamento_membros" => "recrutamento#recrutamento_membros" , as: "recrutamento_membros"
  get "recrutamento_estagios" => "recrutamento#recrutamento_estagios" , as: "recrutamento_estagios"

  post "survey" => "candidatos#survey",:as =>"survey"
  get "inscricao" => "candidatos#inscricao",:as =>"inscricao"
  get "survey_final" => "candidatos#survey_final",:as =>"survey_final"
  get "help" => "comites#help",:as =>"help"
  get "dashboard" => "comites#dashboard",:as =>"dashboard"

  post "edit_candidatos" =>"candidatos#edit_candidatos"

  resources :sessions

   root :to => 'comites#dashboard'

end

app/models/candidato.rb
# -*- encoding : utf-8 -*-
class Candidato < ActiveRecord::Base
  attr_accessible :comite_id, :data_nascimento, :nome, :recrutamento_id, :telemovel, :tipo ,:email


  validates_inclusion_of :tipo, :in => [1,2]
  validates_presence_of :comite_id,:nome,:recrutamento_id
  default_scope :order => 'created_at DESC'
  
  #validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  belongs_to :recrutamento
  has_many :respostas
  has_many :estados

  
  def self.search(search,page,field)
    if page == "all"
      per_page = Candidato.all.count
      page = 1
    else
      per_page = 10
    end


    

    if field == 2
      paginate :per_page => per_page, :page => page,:joins => :estados,
          :conditions => ['estados.nome ILIKE  ? and estados.ultimo = 1', "%#{search}%"]
    else
      paginate :per_page => per_page, :page => page,
          :conditions => ['nome ILIKE  ?', "%#{search}%"]
    end
  end

  #Para que o controller nao fique tao grande
  def self.novo(val,tipo,comite_id,recrutamento_id)
  	new(nome: val[:nome],telemovel: val[:telemovel],data_nascimento: val[:data_nascimento],comite_id: comite_id,tipo: tipo,recrutamento_id: recrutamento_id,email: val[:email])
  end

  def self.last_month(comite_id)
    find(:all, :conditions =>["comite_id = ? and created_at > ?",comite_id, 1.month.ago],:limit => 10)
  end

  def self.last_week
    find(:all, :conditions =>["created_at > ?", 1.week.ago])
  end

  def self.to_csv(options = {},candidato,respostas)
    CSV.generate(options) do |csv|
      csv << column_names
        csv << candidato.attributes.values_at(*column_names)
        respostas.each do |r|
          csv << r.attributes.values_at(*column_names)
        end
    end
  end

  def age(dob)
    #dob = Date.strptime(dob,"%m-%d-%Y")
    #dob = DateTime.parse(dob)
    dob = dob.to_time
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end




  def self.percentagem_idades(recrutamento_id)

    candidatos = find(:all, :conditions =>["recrutamento_id = ?",recrutamento_id])
    idades = Array.new

    stats = Array.new


    candidatos.each do |c|
      idade = c.age(c.data_nascimento)
      
      idades.push([idade,1])
    end

    conver_results = Hash.new { |h,k| h[k] = [] }
    idades.each { |k,v| conver_results[k] << v }
    
    conver_results.each do |i|
      n = i[1].count
      stats.push([i[0].to_s,n])
    end
    
    return stats

  end

  def self.nNao_contactados(recrutamento)
    n = 0

    recrutamento.candidatos.each do |c|
      if c.estados.first.nil?
          n = n + 1
      end      
    end

    return n

  end
  
  def self.est_candidatos(recrutamento)
    lista_estados = Array.new
    stats = Array.new

    recrutamento.candidatos.each do |c|
      if c.estados.first.nil?
          estado = "Nao contactado"
      else
          estado = c.estados.first.nome
      end
      
      lista_estados.push([estado.to_s,1])
    end

    conver_results = Hash.new { |h,k| h[k] = [] }
    lista_estados.each { |k,v| conver_results[k] << v }
    
    conver_results.each do |e|
      n = e[1].count
      stats.push([e[0].to_s,n])
    end

    return stats
  end


  def self.candidatos_estado(candidatos,estado)
    n = 0
    candidatos.each do |c|
      estado_cand = c.estados.first
      if !estado_cand.nil?
        if estado == estado_cand.nome
          n += 1
        end
      end
    end

    return n
  end

  #devolve os candidatos fora de epoca
  # estes candidatos nao possuem recrutemento
  #recrutamento_id = 0
  def self.fora_epoca(comite_id)
    find(:all,:conditions=>["comite_id = ? and recrutamento_id = 0 and activo = 1",comite_id])
  end




  #nao esta a funcionar
  # def self.est_candidatos(recrutamento)
  #   lista_estados = Array.new
  #   num_estados_cand = Array.new
  #   #num_cand = recrutamento_id.candidatos.count

  #   #armazena diferentes estados
  #   recrutamento.candidatos.each do |c|
  #       if c.estados.first.nil?
  #         estado = "Nao contactado"
  #       else
  #         estado = c.estados.first.nome
  #       end
  #       lista_estados.push(estado)
  #   end
  #   #remove estados duplicados
  #   lista_estados.uniq!


  #     recrutamento.candidatos.each do |c|
  #         if c.estados.first.nil?
  #           estado = "Nao contactado"
  #         else
  #           estado = c.estados.first.nome
  #         end

  #         if num_estados_cand.include? estado
  #             num_estados_cand
  #             else
  #               num_estados_cand.push([estado,0])
  #             end
  #             break
  #           end
  #         end
  #       end

  #   return num_estados_cand

  # end

  

end

app/controllers/candidatos_controller.rb
# -*- encoding : utf-8 -*-
class CandidatosController < ApplicationController

before_filter :cand_belongsTo_comite?, :only =>[:show,:edit,:destroy]  

skip_before_filter :authorize, :only => [:inscricao,:survey]


  def candidatos_membros
     recrutamento = current_comite.recrutamento.recrutamento_activo(1)                                                        #vai buscar o recrutamento que esta activo
     
     @candidatos = recrutamento.candidatos.search(params[:search],params[:page],params[:field]) unless  recrutamento.nil?    #vai buscar os candidatos desse recrutamento
     

     @estado = Estado.new
     @estados_recrut = EstadoRecrut.activos(1,current_comite.id)
     @tipo = 1

     if !recrutamento.nil?
       @stats = Candidato.percentagem_idades(recrutamento.id)
       @h = pie_plot(@stats,"Idade Candidatos")

       @stats1 = Candidato.est_candidatos(recrutamento)
       @h1 = pie_plot(@stats1,"Estados Candidatos")
     end
   
  end

  def candidatos_estagios
     recrutamento = current_comite.recrutamento.recrutamento_activo(2)                                     #vai buscar o recrutamento que esta activo
     @candidatos = recrutamento.candidatos.search(params[:search],params[:page],params[:field])  unless  recrutamento.nil?  #vai buscar os candidatos desse recrutamento
     
     @estado = Estado.new
     @estados_recrut = EstadoRecrut.activos(2,current_comite.id)
     @tipo = 2

     if !recrutamento.nil?
       @stats = Candidato.percentagem_idades(recrutamento.id)
       @h = pie_plot(@stats,"Idade Candidatos")

       @stats1 = Candidato.est_candidatos(recrutamento)
       @h1 = pie_plot(@stats1,"Estados Candidatos")
    end

  end

  # altera propriedades das perguntas de um formulario
  # para esta action é passado como argumentos as comboxbox
  # que foram selecionadas nos formulario
  # para cada uma delas é feita a accao que se deseja
  # altera propriedades das perguntas de um formulario
  # para esta action é passado como argumentos as comboxbox
  # que foram selecionadas nos formulario
  # para cada uma delas é feita a accao que se deseja
  def edit_candidatos
    if params[:tipo] == 1
      r = candidatos_membros_path
    else
      r = candidatos_estagios_path
    end

    if !params[:candidatos].nil?
      val = params[:candidatos]
      case params[:commit]
          when "Mudar Estado"
            val.each do |v|
                candidato = Candidato.find(v)
                params[:estado][:candidato_id] = v.to_i
                estado = candidato.estados.build(params[:estado])
                estado.save
             end
             

          when "Enviar Mail"
            n =0
            val.each do |v|
              SendMail.mail_candidato(v,params[:mail],n).deliver
              n = n+1
            end
      end

    end #fim do if

      respond_to do |format|
              format.html { redirect_to  r}
              format.json { head :no_content }
      end
  end
  

  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
    @candidato = Candidato.find(params[:id])
    @estados = @candidato.estados
    
    @estado = Estado.new
    @estados_recrut = EstadoRecrut.activos(@candidato.tipo,current_comite.id)


    respond_to do |format|
      format.html # show.html.erb
      format.csv 
      format.xls  #{ send_data Candidato.to_csv({col_sep: "\t"},@candidato,@candidato.respostas) }
      format.json { render json: @candidato }
    end
  end

  # GET /candidatos/new
  # GET /candidatos/new.json
  def new
    @candidato = Candidato.new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidato }
    end
  end

  #pagina onde o candidato
  # escolhe o comite e se é para estagio ou membro
  def inscricao
    @comites = Comite.all
    render :layout =>"survey"
  end

  def survey
    @comite = Comite.find(params[:cenas][:comite])
    @recrutamento = @comite.recrutamento.activo_and_aberto(params[:cenas][:tipo])
    
    if !@recrutamento.nil?
      @formulario = @comite.formularios.formulario_activo(params[:cenas][:tipo])
      Counter.conta(@recrutamento.id)
      if !@formulario.nil?
        @perguntas_form = @formulario.pergunta_forms
      end
    end

    render :layout =>"survey"
  end

  #guardar respostas de um candidato
  def guardar_survey

     val = params[:respostas]
     @comite = Comite.find(params[:id])
      
     @formulario = @comite.formularios.formulario_activo(params[:tipo])
     @candidato = Candidato.novo(val,params[:tipo],@comite.id,@formulario.recrutamento.id) #cria um novo candidato
     @perguntas = @formulario.pergunta_forms             #vai buscar todas as perguntas do formulario
     rsp = ""
     if @candidato.save
       @perguntas.each do |p|
            if val[p.perguntum_id.to_s].nil?
              rsp = "[Não Respondeu]"
            else
              rsp = val[p.perguntum_id.to_s][:resposta].to_sentence
            end

            Resposta.new(candidato_id: @candidato.id,pergunta_id:p.perguntum_id,resposta:rsp,tipo: params[:tipo]).save
            rsp = ""
      end
     end
     
      respond_to do |format|
      format.html { redirect_to survey_final_path }
      format.json { head :no_content }
    end
  end

  def survey_final
    render :layout =>"survey"
  end


  def candidatos_fora_epoca
    @candidatos = Candidato.fora_epoca(current_comite.id)
  end

  def guardar_cand_fora_epoca
      val = params[:respostas]
      comite_id = params[:id]
      tipo = params[:tipo]
      @candidato = Candidato.novo(val,tipo,comite_id,0) #cria um novo candidato

      @candidato.save

      respond_to do |format|
        format.html { redirect_to survey_final_path }
        format.json { head :no_content }
      end
  end

  # GET /candidatos/1/edit
  def edit
    @candidato = Candidato.find(params[:id])
    @estado = Estado.new
  end

  # POST /candidatos
  # POST /candidatos.json
  def create
    @candidato = Candidato.new(params[:candidato])

    respond_to do |format|
      if @candidato.save

        params[:estado][:candidato_id] = @candidato.id
        @estado = Estado.new(params[:estado]).save
        format.html { redirect_to @candidato, notice: 'Candidato was successfully created.' }
        format.json { render json: @candidato, status: :created, location: @candidato }
      else
        format.html { render action: "new" }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidatos/1
  # PUT /candidatos/1.json
  def update
    @candidato = Candidato.find(params[:id])

    respond_to do |format|
      if @candidato.update_attributes(params[:candidato])
        format.html { redirect_to @candidato, notice: 'Candidato was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy
    @candidato = Candidato.find(params[:id])
    @candidato.activo = 0

    @candidato.save

    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/candidatos_helper.rb
# -*- encoding : utf-8 -*-
module CandidatosHelper
	
	def estadoToLabel(estado)
		if !estado.nil?
			return "<span class='label label-info'>#{estado.nome}</span>".html_safe
		else
			return "<span class='label label-warning'>Não Contactado</span>".html_safe
		end
	end	

	
	def tipoToStringLabel(tipo)
		tipo == 1 ? "<span class='label label-success'>Membros</span>".html_safe : "<span class='label label-info'>&nbsp;Estagio&nbsp;&nbsp;</span>".html_safe
	end

	def age(dob)
	  #dob = Date.strptime(dob,"%m-%d-%Y")
	  #dob = DateTime.parse(dob)
	  dob = dob.to_time
	  now = Time.now.utc.to_date
	  now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
	end

	def getUltimoUpdate
		if @estados.blank?
			"Sem alteracoes"
		else
			@estados.first.updated_at.to_formatted_s(:short)
		end
	end

end

app/views/candidatos/_candidatos_fora.html.erb
<%= form_for(:candidatos, :html=>{:id =>"form_candidatos"},:url => {:action => 'edit_candidatos',:controller => 'candidatos'},:multipart => true) do |f| %>

  <div class="container-fluid">
        <div class="well">
          <table class="table table-hover table-striped sortable1">
            <thead>
              <tr>
                <th><input type="checkbox" name="select-all" id="select-all"></th>
                <th data-sort="string">Nome</th>
                <th>Telemovel</th>
                <th data-sort="string">Idade</th>
                <th data-sort="string">Email</th>
                <th data-sort="string">Data Registo</th>
                <th data-sort="string">Tipo</th>
                <th data-sort="string">Estado</th>
                <th style="width: 26px;"></th>
                <th style="width: 26px;"></th>
              </tr>
            </thead>
            <tbody>
              <% @candidatos.each do |candidato| %>
                <tr>
                  <td><%= check_box_tag 'candidatos[]', candidato.id, false ,:class=>"select-all" %></td>
                  <td><%= candidato.nome %></td>
                  <td id="tel<%= candidato.id %>" value="<%= candidato.email %>"><%= candidato.telemovel %></td>
                  <td><%= age(candidato.data_nascimento) %></td>
                  <td id="email<%= candidato.id %>" value="<%= candidato.email %>"><%= candidato.email %></td>
                  <td><%= candidato.created_at.strftime('%d %b') %>(<%=  time_ago_in_words(candidato.created_at) %>)</td>
                  <td><b><%= tipoToString(candidato.tipo) %><b></td>

                  <td>
                   <span class='label label-warning'>Fora de Época</span>
                  </td>
                  <td>
                      <%= link_to '<i class="icon-remove"></i>'.html_safe, candidato, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>

      
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          Obter
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
           <li id="mail" value="candidatos[]"> <a href="#" >Obter Emails</a></li>
           <li id="telemovel" value="candidatos[]"><a href="#" >Obter Telemovel</a></li>
          <!-- <li><a id="email_nao_contactados">Obter Emails de não contactados</a></li>-->
          <!-- dropdown menu links -->
        </ul>
    </div>
</div>

      <div id="askDialog" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="windowTitleLabel" aria-hidden="true">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3 id="askDialogPrompt"> </h3>
        </div>
      <div class="modal-body" id="askDialogBody">
      
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
   </div>

  <div id="askDialog1222" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="windowTitleLabel" aria-hidden="true">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3 id="askDialogPrompt"> </h3>
        </div>
      <div class="modal-body" id="askDialogBody">
          Tens de seleccionar pelo menos um candidato
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
   </div>

   


<% end %><!--fim do form-->

app/views/candidatos/_estado.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= estado.nome %>
</p>

<p>
  <b>Data:</b>
  <%= estado.data %>
</p>

<p>
  <b>Descricao:</b>
  <%= estado.descricao %>
</p>

<p>
  <b>Responsavel:</b>
  <%= estado.responsavel %>

</p>
<p>
	<b>CAndl:</b>
<%= estado.candidato_id %>

<%= link_to 'Edit', edit_estado_path(estado) %> |
<%= link_to 'Back', estados_path %>

app/views/candidatos/_estados.html.erb
<div class="container-fluid">
      <div class="well">

          <h1>Listing estados</h1>

          <table class="table table-striped">
            <tr>
              <th></th>
              <th>Nome</th>
              <th>Data</th>
              <th>Descricao</th>
              <th>Responsavel</th>
              <th>Ultima Actualização</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>

          <% @estados.each do |estado| %>
            <tr>
              <td class="show" id="<%= estado.id %>"><%= link_to "VER", "#myModalEstadoPrevis", "data-toggle" => "modal" %></td>
              <td><%= estado.nome %></td>
              <td><%= estado.data %></td>
              <td><%= estado.descricao %></td>
              <td><%= estado.responsavel %></td>
              <td><%= l estado.updated_at ,:format => :time %></td>
              <td><%= link_to 'Show', estado %></td>
              <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
              <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </table>

          <br />
      </div>
    </div>

 <!-- Modal ESTDO-->
<div id="myModalEstadoPrevis" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Novo Estado</h3>
    </div>
    <div id="modal-bodyEstado">
       
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
       <button class="btn btn-primary" name="commit" value="Mudar Estado"><i class="icon-save"></i> Mudar Estado</button>
    </div>
  </div>

app/views/candidatos/_form_estados.html.erb
<%= fields_for :estado, @estado do |f| %>
<div class="field">
    <% f.label :nome %><br />

    <%= f.select :nome, @estados_recrut.collect {|p| [ p.nome, p.nome ] } + ['Outro'] , :prompt => 'Escolha um'%>

    
    <%= f.text_field :nome,:placeholder =>"Nome estado" %>
  </div>

  <div class="field">
    <% f.label :data %>
    <%= f.hidden_field :data,value: Time.now %>
  </div>
  <div class="field">
    <% f.label :descricao %><br />
    <%= f.text_area :descricao ,:size=>"400*39",:class=>"allowEnter",:placeholder =>"Descrição"%>
  </div>
  <div class="field">
    <% f.label :responsavel %><br />
    <%= f.text_field :responsavel ,:placeholder =>"Responsavel"%>
  </div>

<% end %>

app/views/candidatos/_respostas.html.erb
<div class="container-fluid">
      <div class="well">
        <table class="table table-striped">
            <% @candidato.respostas.each do |r| %>
                <tr>
                   <td><%= getPergunta(r.pergunta_id).titulo %></td>
                   <td><h6><%= r.resposta %></h6></td>
                </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>

app/views/candidatos/edit.html.erb
<h1>Editing candidato</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidato %> |
<%= link_to 'Back', candidatos_path %>

app/views/candidatos/new.html.erb
<h1>New candidato</h1>

<%= render 'form' %>

<%= link_to 'Back', candidatos_path %>

app/views/candidatos/show.html.erb
          
<ul class="breadcrumb">
      <li><a href="index.html">Home</a> <span class="divider">/</span></li>
      <li class="active">Perfil Candidato</li>
</ul>


<p id="notice"><%= notice %></p>



  <!-- verifica se tem algum estado, se tiver mostra-->
        
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
      <li class="active"><a href="#pane1" data-toggle="tab">Info</a></li>
      <li><a href="#pane2" data-toggle="tab">Respostas</a></li>
      <li><a href="#pane3" data-toggle="tab">Estados</a></li>

  </ul>
  <div class="tab-content">
    <div id="pane1" class="tab-pane active">
      

          <div class="span6 well" >
                  <table class="table table-striped table-condensed">
                      <tbody><tr>
                          <td><h6>Nome:</h6></td>
                          <td><i class="icon-user"></i> <%= @candidato.nome %></td>
                      </tr>
                      <tr>
                          <td><h6>Telemovel:</h6></td>
                          <td><i class="icon-home"></i> <%= @candidato.telemovel %></td>
                      </tr>
                      <tr>
                          <td><h6>Email:</h6></td>
                          <td><i class="icon-envelope"></i> <%= @candidato.email %></td>
                      </tr>
                      <tr>
                          <td><h6>Idade:</h6></td>
                          <td><i class="icon-headphones"></i> <%= age(@candidato.data_nascimento) %> Anos</td>
                      </tr>
                      
                      <tr>
                          <td><h6>Data Registo:</h6></td>
                          <td><i class=" icon-calendar"></i> <%= @candidato.created_at.strftime('%d %b') %>(<%=  time_ago_in_words(@candidato.created_at) %>)</td>
                      </tr>
                  </tbody></table>
          </div>


          <div class="span4">
                          <div id="reports" class="well">
                              <h3 class="modal-header"> Registou-se há <%=  time_ago_in_words(@candidato.created_at)  %></h3>
                                <% if  !@candidato.estados.last.nil? %>
                                    <p>
                                        <b>Estado Actual</b>
                                        <span title="Alterar Estado" class="label label-success">
                                          <%= @candidato.estados.first.nome %>
                                        </span>
                                    </p>
                                  <% else %>
                                    <p>
                                      <b>Estado Actual</b>
                                      <span title="Alterar Estado" class="label label-warning">
                                            Não contactado
                                      </span>
                                    </p>
                                  <% end %>


                          <ul class="nav nav-list">
                              <li>
                              <div class="alert alert-info no-reports">
                                 <p class="list-item"><b>Ultima actualização:</b><%= getUltimoUpdate %> </p>
                                
                              </div>
                            </li>
                          </ul>
                      </div>
              </div>
    </div>

     <div id="pane2" class="tab-pane">
      <%= render 'respostas' %>
    </div>

     <div id="pane3" class="tab-pane">
        
        <div class="row">
                <div class="span13">
                  <div class="tabbable">
                    <ul class="nav nav-tabs">
                    <li class="active"><a href="#1" data-toggle="tab">Estados</a></li>
                    <li><a href="#2" data-toggle="tab">Estatistica</a></li>
                    </ul>
                        <div class="tab-content">
                        <div class="tab-pane active" id="1">
                            <%= render 'estados', collection: @estados %>
                        </div>
                        <div class="tab-pane" id="2">
                           
                        </div>    
                    </ul>
                  </div>
                </div>
              </div>
        </div>

    </div>

</div>



 <div class="btn-toolbar">
          <a href="#myModalEstado" data-toggle="modal" class="btn"><i class="icon-plus"></i>Novo Estado</a>
</div>







<%= link_to 'Edit', edit_candidato_path(@candidato) %> |
<%= link_to 'Back', candidatos_path %>



 <!-- Modal ESTDO-->
<div id="myModalEstado" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Novo Estado</h3>
    </div>
    <div class="modal-body">
       <%= render :partial=>'estados/form' , :locals => { :candidato => @candidato.id } %>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>