config/routes.rb
Gestor::Application.routes.draw do
  
  get "estado_recrut/new"

  get "estado_recrut/create"

  get "estado_recrut/destroy"

  get "estado_recrut/edit"

  resources :estados

  resources :candidatos do
    member do
      post :guardar_survey
      post :guardar_cand_fora_epoca
    end
  end

  get "recrutamento/create"

  get "recrutamento/new"

  resources :pergunta_forms do
    member do
      post :edit_pergunta_form
    end
  end

  get "password_resets/new"

  resources :pergunta do
    member do
      post :importar_pergunta_form
    end
  end

  get "sessions/new"

  resources :comites do
    member do
      post :guardar
      post :reorder
      post :reorderEstados
      get :abrir_recrutamento
      post :add_estado
    end
  end

  resources :recrutamento
  
  resources :estado_recrut do
    member do
      post :create_estado
      put :update_estado
    end
  end

  get "abrir_recrutamento" => "recrutamento#abrir_recrutamento_m"
  get "abrir_inscricoes" => "recrutamento#abrir_inscricoes"
  get "fechar_inscricoes" => "recrutamento#fechar_inscricoes"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "comites#new", :as => "sign_up"

  get "inscricoes" => "comites#inscricoes", :as => "inscricoes"
  get "profile" => "comites#show", :as => "profile"

  post "pre_vis_survey" =>"comites#pre_vis_survey", :as => "pre_vis_survey"
  

  get "perguntas_comite/:id" => "pergunta#perguntas_comite",:as =>"perguntas_comite"

  
  get "formulario_membros/:id" => "comites#formulario_membros",:as =>"formulario_membros"
  get "formulario_estagios/:id" => "comites#formulario_estagios",:as =>"formulario_estagios"
  
  get "comites/:id/survey" => "comites#survey",:as =>"survey"

  get "candidatos_membros" => "candidatos#candidatos_membros" , as: "candidatos_membros"
  get "candidatos_estagios" => "candidatos#candidatos_estagios" , as: "candidatos_estagios"
  get "candidatos_fora_epoca" => "candidatos#candidatos_fora_epoca" , as: "candidatos_fora_epoca"

  get "recrutamento_membros" => "recrutamento#recrutamento_membros" , as: "recrutamento_membros"
  get "recrutamento_estagios" => "recrutamento#recrutamento_estagios" , as: "recrutamento_estagios"

  post "survey" => "candidatos#survey",:as =>"survey"
  get "inscricao" => "candidatos#inscricao",:as =>"inscricao"
  get "survey_final" => "candidatos#survey_final",:as =>"survey_final"
  get "help" => "comites#help",:as =>"help"
  get "dashboard" => "comites#dashboard",:as =>"dashboard"

  post "edit_candidatos" =>"candidatos#edit_candidatos"

  resources :sessions

   root :to => 'comites#dashboard'

end

app/models/estado.rb
# -*- encoding : utf-8 -*-
class Estado < ActiveRecord::Base
  attr_accessible :data, :descricao, :nome, :responsavel,:candidato_id

  validates_presence_of :nome,:candidato_id
  default_scope :order => 'created_at DESC'

  belongs_to :candidato
end

app/controllers/estados_controller.rb
# -*- encoding : utf-8 -*-
class EstadosController < ApplicationController

  before_filter :correct_comite, :only => [  :destroy,:edit ]
  # GET /estados
  # GET /estados.json
  def index #tem de sair
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.json
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.json
  def create
    
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render json: @estado, status: :created, location: @estado }
      else
        format.html { render action: "new" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.json
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to estados_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/estados_helper.rb
# -*- encoding : utf-8 -*-
module EstadosHelper
end

app/views/estados/_estados.html.erb
<h1>Listing estados</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Data</th>
    <th>Descricao</th>
    <th>Responsavel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estados.each do |estado| %>
  <tr>
    <td><%= estado.nome %></td>
    <td><%= estado.data %></td>
    <td><%= estado.descricao %></td>
    <td><%= estado.responsavel %></td>
    <td><%= link_to 'Show', estado %></td>
    <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
    <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/estados/_form.html.erb
<%= form_for(@estado) do |f| %>
  <% if @estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% @estado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% f.label :nome %><br />
    <%= f.select :nome, @estados_recrut.collect {|p| [ p.nome, p.nome ] } + ['Outro'] , :prompt => 'Escolha um'%>

    
    <%= f.text_field :nome,:placeholder =>"Nome estado" %>
  </div>

  <div class="field">
    <% f.label :data %>
    <%= f.hidden_field :data,value: Time.now %>
  </div>
  <div class="field">
    <% f.label :descricao %><br />
    <%= f.text_area :descricao ,:size=>"400*39",:class=>"allowEnter",:placeholder =>"Descrição"%>
  </div>
  <div class="field">
    <% f.label :responsavel %><br />
    <%= f.text_field :responsavel ,:placeholder =>"Responsavel"%>
  </div>

   <div class="field">
    <% f.label :candidato_id %><br />
    <%= f.text_field :candidato_id ,value: candidato %>
  </div>

  <button class="btn btn-primary"  href="#"><i class="icon-plus"></i> Adicionar Estado</button>

  
<% end %>

app/views/estados/edit.html.erb
<h1>Editing estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<h1>Listing estados</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Data</th>
    <th>Descricao</th>
    <th>Responsavel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estados.each do |estado| %>
  <tr>
    <td><%= estado.nome %></td>
    <td><%= estado.data %></td>
    <td><%= estado.descricao %></td>
    <td><%= estado.responsavel %></td>
    <td><%= link_to 'Show', estado %></td>
    <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
    <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New estado</h1>

<%= render 'form' %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @estado.nome %>
</p>

<p>
  <b>Data:</b>
  <%= @estado.data %>
</p>

<p>
  <b>Descricao:</b>
  <%= @estado.descricao %>
</p>

<p>
  <b>Responsavel:</b>
  <%= @estado.responsavel %>

</p>
<p>
	<b>CAndl:</b>
<%= @estado.candidato_id %>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>