config/routes.rb
Gestor::Application.routes.draw do
  
  get "estado_recrut/new"

  get "estado_recrut/create"

  get "estado_recrut/destroy"

  get "estado_recrut/edit"

  resources :estados

  resources :candidatos do
    member do
      post :guardar_survey
      post :guardar_cand_fora_epoca
    end
  end

  get "recrutamento/create"

  get "recrutamento/new"

  resources :pergunta_forms do
    member do
      post :edit_pergunta_form
    end
  end

  get "password_resets/new"

  resources :pergunta do
    member do
      post :importar_pergunta_form
    end
  end

  get "sessions/new"

  resources :comites do
    member do
      post :guardar
      post :reorder
      post :reorderEstados
      get :abrir_recrutamento
      post :add_estado
    end
  end

  resources :recrutamento
  
  resources :estado_recrut do
    member do
      post :create_estado
      put :update_estado
    end
  end

  get "abrir_recrutamento" => "recrutamento#abrir_recrutamento_m"
  get "abrir_inscricoes" => "recrutamento#abrir_inscricoes"
  get "fechar_inscricoes" => "recrutamento#fechar_inscricoes"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "comites#new", :as => "sign_up"

  get "inscricoes" => "comites#inscricoes", :as => "inscricoes"
  get "profile" => "comites#show", :as => "profile"

  post "pre_vis_survey" =>"comites#pre_vis_survey", :as => "pre_vis_survey"
  

  get "perguntas_comite/:id" => "pergunta#perguntas_comite",:as =>"perguntas_comite"

  
  get "formulario_membros/:id" => "comites#formulario_membros",:as =>"formulario_membros"
  get "formulario_estagios/:id" => "comites#formulario_estagios",:as =>"formulario_estagios"
  
  get "comites/:id/survey" => "comites#survey",:as =>"survey"

  get "candidatos_membros" => "candidatos#candidatos_membros" , as: "candidatos_membros"
  get "candidatos_estagios" => "candidatos#candidatos_estagios" , as: "candidatos_estagios"
  get "candidatos_fora_epoca" => "candidatos#candidatos_fora_epoca" , as: "candidatos_fora_epoca"

  get "recrutamento_membros" => "recrutamento#recrutamento_membros" , as: "recrutamento_membros"
  get "recrutamento_estagios" => "recrutamento#recrutamento_estagios" , as: "recrutamento_estagios"

  post "survey" => "candidatos#survey",:as =>"survey"
  get "inscricao" => "candidatos#inscricao",:as =>"inscricao"
  get "survey_final" => "candidatos#survey_final",:as =>"survey_final"
  get "help" => "comites#help",:as =>"help"
  get "dashboard" => "comites#dashboard",:as =>"dashboard"

  post "edit_candidatos" =>"candidatos#edit_candidatos"

  resources :sessions

   root :to => 'comites#dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>AIESEC</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

   
     <%= stylesheet_link_tag "application-all", :media => "all" %>
     <!-- este javascript esta aqui por causa dos graficos sem ele nao funcionam-->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .brand { font-family: georgia, serif; }
        .brand .first {
            color: #ccc;
            font-style: italic;
        }
        .brand .second {
            color: #fff;
            font-weight: bold;
        }

        a.hover {
            color: #fff;
             background-color: #000;
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body  > 
  <!--<![endif]-->
    
   <div class="navbar">
        <div class="navbar-inner">
                <ul class="nav pull-right">
                <% if current_comite %>
                    <!--<li><a href="#" class="hidden-phone visible-tablet visible-desktop" role="button">Settings</a></li>-->
                    <li id="fat-menu" class="dropdown">
                        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-user"></i> <%= current_comite.nome %>
                            <i class="icon-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Dados do LC", profile_path %></li>
                            <li class="divider"></li>
                            <li><%= link_to "Log out", log_out_path %></li>
                        </ul>
                    </li>
                    <% else %>
                        <%= link_to "Sign up", sign_up_path %> or
                        <%= link_to "log in", log_in_path %>
                      <% end %>
                    <% m = current_comite.nome.split(' ') %>
                </ul>
                <a class="brand" href="/dashboard"><span class="first"><%= m[0] %></span> <span class="second"><%= m[1] %></span></a>
        </div>
    </div>


    


    
    <div class="sidebar-nav">
        
        <a href="/dashboard" class="nav-header collapsed" data-toggle="collapse"><i class="icon-dashboard"></i>Home</a>
        
         <a href="#recrutamentos-menu" class="nav-header collapsed in" data-toggle="collapse"><i class="icon-globe"></i>Recrutamentos<i class="icon-chevron-up"></i></a>
        <ul id="recrutamentos-menu" class="nav nav-list collapse in">
            <li ><%= link_to "Recrutamentos Membros" ,  recrutamento_membros_path %></li>
            <li ><%= link_to "Recrutamentos Estagios" ,  recrutamento_estagios_path %></li>
        </ul>
        

        <a href="#inscricoes-menu" class="nav-header collapsed in" data-toggle="collapse"><i class="icon-user"></i>Gestão de inscrições<i class="icon-chevron-up"></i></a>
        <ul id="inscricoes-menu" class="nav nav-list collapse in">
            <li ><%= link_to "Candidatos Membros" ,  candidatos_membros_path %></li>
            <li ><%= link_to "Candidatos Estagios" ,  candidatos_estagios_path %></li>
        </ul>


        
         <a href="#formularios-menu" class="nav-header" data-toggle="collapse"><i class="icon-list"></i>Formulários <i class="icon-chevron-up"></i></a>
        <ul id="formularios-menu" class="nav nav-list collapse in">
            <li ><%= link_to "Perguntas",perguntas_comite_path(current_comite) %></li>
            <li ><a href="/formulario_membros/<%= current_comite.id unless !signed_in? %>">Membros</a></li>
            <li ><a href="/formulario_estagios/<%= current_comite.id unless !signed_in? %>">Estágiarios</a></li>

        </ul>
        
      <!--   <a href="#relatorio-menu" class="nav-header" data-toggle="collapse"><i class="icon-signal"></i>Relatórios</a>
        <ul id="relatorio-menu" class="nav nav-list collapse">
          <li ><a href="users.html">Estágiarios</a></li>
            <li ><a href="404.html">Membros</a></li>
        </ul> -->
        
        
        
        <a href="#accounts-menu" class="nav-header collapsed" data-toggle="collapse"><i class="icon-globe"></i><%= current_comite.nome %><i class="icon-chevron-up"></i></a>
        <ul id="accounts-menu" class="nav nav-list collapse in">
            <li ><%= link_to "Dados do LC", profile_path %></li>
            <li ><%= link_to "Inscrições", inscricoes_path %></li>
            <li ><%= link_to "Candidatos fora de epoca", candidatos_fora_epoca_path %></li>
            <li ><%= link_to "Survey", inscricao_path %></li>
           
        </ul>

        
        
            

       <!-- <a href="/help" class="nav-header" ><i class="icon-question-sign"></i>Help</a>-->
        <!--<a href="faq.html" class="nav-header" ><i class="icon-comment"></i>Faq</a>-->
    </div>
    
<div class="content">
          <%= yield %>

                    <footer>
                        <hr>

                        <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
                        <p class="pull-right">BY <a href="http://aiesec.pt" target="_blank">AIESEC Minho</a></a></p>

                        <p>&copy; 2012 <a href="http://aiesec.pt" target="_blank">AIESEC</a></p>
                    </footer>
                    
            </div>
        </div>
    </div>

    <span class="totop" style="display: block; "><a href="#"><i class="icon-chevron-up"></i></a></span>
    
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    
  </body>
</html>

app/views/layouts/log_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>AIESEC</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag "application-all", :media => "all" %>



    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
      <!-- Demo page code -->

    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .brand { font-family: georgia, serif; }
        .brand .first {
            color: #ccc;
            font-style: italic;
        }
        .brand .second {
            color: #fff;
            font-weight: bold;
        }

        body {
          background-image: url(/assets/aiesec.jpg);
          background-size:1300px 650px;
          background-repeat:no-repeat;
        }
    </style>

  <body> 
  <!--<![endif]-->
    
    <div class="navbar">
        <div class="navbar-inner">
                <ul class="nav pull-right">
                    
                </ul>
                <a class="brand" href="index.html"><span class="first"></span>AIESEC <span class="second">Portugal</span></a>
        </div>
    </div>
    

    <%= yield %>

    


    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
      
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>
    
  </body>
</html>

app/views/layouts/sign_up.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap Admin</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag "application-all", :media => "all" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body class=""> 
  <!--<![endif]-->
    
    <div class="navbar">
        <div class="navbar-inner">
                <ul class="nav pull-right">
                    
                </ul>
                <a class="brand" href="index.html"><span class="first">Aiesec</span> <span class="second">Portugal</span></a>
        </div>
    </div>
    


    
 <%= yield %>
    


    


    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
      
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>
    
  </body>
</html>

app/views/layouts/survey.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>AIESEC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A calm, blue sky.">
    <meta name="author" content="Thomas Park">

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag "bootstrapmin_survey.css" %>
    <%= stylesheet_link_tag "datepicker.css" %>


   <script type="text/javascript">

     var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23019901-1']);
      _gaq.push(['_setDomainName', "bootswatch.com"]);
        _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);
      
     (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

   </script>

  </head>

  <body class="preview" id="top" data-spy="scroll" data-target=".subnav" data-offset="80">
    <script src="../js/bsa.js"></script>


  <!-- Navbar
    ================================================== -->
 <div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <%= link_to image_tag( 'logo.png') %>
      
     </div>
   </div>
 </div>

    <div class="container">


<!-- Masthead
================================================== -->
<header class="jumbotron subhead" id="overview">
  <div class="row">
    <div class="span6">
      <p class="lead">A calm, blue sky.</p>
    </div>
    
  </div>
  <div class="subnav">
    <ul class="nav nav-pills">
      
    </ul>
  </div>
</header>

<%= yield %>

<br><br><br><br>

     <!-- Footer
      ================================================== -->
      <hr>

      <footer id="footer">
        <p class="pull-right"><a href="#top">Back to top</a></p>
        <div class="links">
          
        </div>
        Made by <a href="http://aiesec.pt">AIESEC</a>.</p>
      </footer>

    </div><!-- /container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    



  </body>
</html>